kytos-ng/kytos-end-to-end-tests

tests/test_e2e_05_topology.py

- Test disabled switch on start
- Test disabling a switch
- Test removing switch metadata
- Test removing interface metadata

Inclusion of some new tests, such as:

---

tests/test_e2e_20_flow_manager.py

Tests to check if a changed or added flow outside kytos is reverted or removed by the consistency check.

Tests for flow manager consistency check

---

tests/test_e2e_01_kytos_startup.py

The tests on "test_e2e_01_kytos_startup" and the structure has been unified to a unique test environment, PyTest, following the structure and methodology brought by this framework.

Unifying the tests on "test_e2e_01_kytos_startup"

---

tests/test_e2e_20_flow_manager.py

- Replace a flow action on the switch and make sure kytos will reconfigure.
- Add a flow action on the switch and make sure Kytos will reconfigure.
- Create an additional flow on table 0 and check if Kytos will remove it.

New Consistency Tests

---

tests/test_e2e_05_topology.py
tests/test_e2e_10_mef_eline.py
tests/test_e2e_12_mef_eline.py
tests/test_e2e_20_flow_manager.py
tests/test_e2e_21_flow_manager.py
tests/test_e2e_30_of_lldp.py

This PR changes some of the waiting timers of many tests to use a standard value, reducing the duration of the tests according (see #37)

Making the delay between tests uniform

---

tests/helpers.py

- Minimum cosmetics changes :-P

---

tests/test_e2e_10_mef_eline.py

This PR implements a new stress test on mef_eline with the creation and removal of 10 circuits, 10 times. Thanks to this test, we could identify a race condition in mef_eline (https://github.com/kytos-ng/mef_eline/issues/22) and flow_manager (https://github.com/kytos-ng/flow_manager/issues/12)

Add a new stress test that creates and removes 10 circuits 10 times

---

tests/test_e2e_15_maintenance.py

This PR includes a new test, close related to maintenance, and the latest contributions focused on a new feature that allows extending running maintenance.
The new test verifies the action to extend an ended maintenance.
Whit this last test, we cover all the current features relatives to maintenance over a switch.

Inclusion of a new test

---

tests/test_e2e_20_flow_manager.py

- Improvement over API get calls
- Minor changes following PEP8 convention
- Inclusion of a new test to retrieve and verify the status of all the flows

An improvement over the e2e tests focused on the flow manager Napp

---

tests/test_e2e_20_flow_manager.py
tests/test_e2e_21_flow_manager.py

- Fixing API call response /flow_manager/v2/flows/{dpid} on POST
- Fixing API call response /flow_manager/v2/flows/{dpid} on DELETE

Fixes unrelated response code returned by flow_manager NApp in POST and DELETE API's calls

---

tests/test_e2e_15_maintenance.py
tests/test_e2e_23_flow_manager.py

- It is removed xfail actions to activate some tests evaluation and outcome.
- It is fixed the returning code after the Post API call to install a flow.
- Is performed some improvements on the modules imported, and the code has been cleaned up.
N/A

Minor changes related to performance and documentation

---

tests/test_e2e_13_mef_eline.py

Due to mef_eline issue https://github.com/kytos-ng/mef_eline/issues/58 we need such decorators

Adding xfail decorator to known issues

---

tests/test_e2e_10_mef_eline.py

This PR will add a new test to kytos-ng/mef_eline to evaluate the usage of EVC's metadata, introduced by https://github.com/kytos-ng/mef_eline/pull/84.

Add test to evaluate mef_eline evc metadata

---

tests/helpers.py

Fixes #118 
This PR leverages the `GET /api/kytos/core/status` REST API to check on the controller status and wait until it finishes the startup process. A maximum wait of 60 seconds was configured to avoid waiting forever. It is important to wait until the controller finishes the startup process because, [since Kytos will fork and return to the user at the beginning of the startup process](https://github.com/kytos-ng/kytos/blob/master/kytos/core/kytosd.py#L107-L108), the user may send API requests when Kytos is not ready. Similarly, switches may be trying to connect when Kytos is not ready yet. Both situations will result in failures on the end-to-end tests.
The failures are especially noticed in an overloaded scenario (such as the one described in issue #118) because the controller …

Add wait routine to allow controller finishes its startup process

---

kytos-init.sh
tests/test_e2e_31_of_lldp.py

Fixes #136 
Added TestE2EOfLLDP test suite to cover link liveness.
This PR depends on this branch `of_lldp` [branch](https://github.com/kytos-ng/of_lldp/pull/56)

[Feature] Added test suite for of_lldp link liveness

---

tests/test_e2e_15_maintenance.py

Fixes #145 
Updated `test_010_create_mw_on_switch_should_move_evc` to avoid false positive during convergence. 
Here's the rationale:
- Since we currently have a very low and aggressive `CONSISTENCY_MIN_VERDICT_INTERVAL = 3`, `flow_manager` consistency check could prematurely kicks in. So, instead of checking flows mid-convergence, I've replaced it to check the output of the EVC of the `current_path` on `GET /v2/evc/<evc_id>`, confirming that it switched and also a ping between hosts.
- I've maintained `dump-flows` asserts, however only at the beginning and at the end of the test where we have a relatively large interval where it shouldn't be converging anymore. If we hit more issues when checking the flows, then it's because it never converged (or NApps aren't deleting/installing flows …

Updated `test_010_create_mw_on_switch_should_move_evc` to avoid false positive during convergence

---

tests/test_e2e_20_flow_manager.py

Fixes #31 
- Augmented `test_025_delete_flows` to cover `GET /v2/stored_flows` and `GET /v2/flows`
I ran this `test_025_delete_flows` three times, all iterations succeeded:
```
+ for i in {1..3}
+ echo 'iteration 3'
iteration 3
+ python3 -m pytest tests/ --timeout=300 -k test_025_delete_flows
timeout: 300.0s
collected 200 items / 199 deselected / 1 selected
tests/test_e2e_20_flow_manager.py .                                      [100%]
test_e2e_20_flow_manager.py: 17 warnings …
```

Augmented `test_025_delete_flows` to cover `GET /v2/stored_flows` and `GET /v2/flows`

---

tests/test_e2e_20_flow_manager.py

This complements PR #175
I augmented `test_005_install_flow` to also cover `GET /v2/stored flows` installed state.
I ran it three times:
```
+ for i in {1..3}
+ echo 'iteration 3'
iteration 3
+ python3 -m pytest tests/ --timeout=300 -k 'test_e2e_20_flow_manager and test_005_install_flow' -vv
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
timeout: 300.0s
collecting ... collected 200 items / 199 deselected / 1 selected
tests/test_e2e_20_flow_manager.py::TestE2EFlowManager::test_005_install_flow PASSED [100%]
=============================== warnings summary …
```

Augment test to also cover `GET /v2/stored flows` installed state

---

docker-compose.yml
scripts/wait_for_mongo.py
tests/test_e2e_41_kytos_auth.py

Closes #164
Closes #163 
This is a first draft. These tests are working but I am wondering about this:
-Do I verify that the data has been modified? Right now it just asserts a successful response but, in the case of `delete` Do I verify that the key `deleted_at` has no longer the value `None`?

Added e2e tests for auth endpoints

---

tests/test_e2e_10_mef_eline.py

Tests for changes from `mef_eline` PR [#214](https://github.com/kytos-ng/mef_eline/pull/214)

Modified tests to test priority default values

---

tests/test_e2e_50_maintenance.py

This PR updates maintenance tests to use the newer maintenance API being introduced in kytos-ng/maintenance#64.

Updated maintenance tests to latest api

---

tests/test_e2e_40_sdntrace.py

Related to PR [70 in sdntrace_cp](https://github.com/kytos-ng/sdntrace_cp/pull/70)
Add `test_040_run_sdntrace_no_action` into `test_e2e_40_sdntrace` to evaluate the case of flows with empty action
A topology with ten switches is used:
2 S1 2 ---- 2 S2 3 ---- 2 S3 3 ---- 2 S3 3 ---- ... ---- 2 S10
- On S1, a flow matching port 2 and output port 2 is pushed.
- On S2, a flow matching port 2 and output port 3 is pushed.
- Then on S3, it matches on port 2 and empty action.
The output of sdntrace_cp shows (correctly) that the trace doesn't complete: The path has only two steps and the second one has type `trace` instead of `last`
+ python3 -m pytest tests/test_e2e_40_sdntrace.py::TestE2ESDNTrace::test_040_run_sdntrace_no_action
============================= test session starts …

feature: Add test for flows without actions

---

tests/test_e2e_10_mef_eline.py

Related to `mef_eline` PR [#298](https://github.com/kytos-ng/mef_eline/pull/298)
Added a test for bulk updates

Added test for bulk updates

---

tests/test_e2e_01_kytos_startup.py
tests/test_e2e_60_of_multi_table.py

Closes #232 
Added tests for `of_multi_table`.
```
plugins: timeout-2.1.0, rerunfailures-10.2, anyio-3.6.2
collected 5 items
tests/test_e2e_60_of_multi_table.py .....   
```

Added tests for `of_multi_table`

---

tests/test_e2e_40_sdntrace.py

Closes #247 
Add `test_085_test_evcs_terminating_on_nnis` test to include the case of EVCs terminating on NNIs in the e2e tests.

Add test for evc terminating on NNI

---

tests/test_e2e_40_sdntrace.py

Closes #312
This PR depends in sdntrace [PR](https://github.com/kytos-ng/sdntrace/pull/80)
Added tests for `sdntrace` support for TCP and UDp
N/A
```
+ python3 -m pytest tests/test_e2e_40_sdntrace.py --reruns 2 -r fEr
collected 16 items
tests/test_e2e_40_sdntrace.py ................                           [100%]
```

Added sdntrace for TCP and UDP

---

tests/test_e2e_20_flow_manager.py

Closes #319 
Add test case to cover same match but different cookie values
I'll dispatch an exec shortly and update here
It's passing with the related branches:
```
+ python3 -m pytest tests -k test_011_install_flows_same_match_diff_cookie --reruns 2 -r fEr
collected 264 items / 263 deselected / 1 selected
tests/test_e2e_20_flow_manager.py .                                      [100%]
========== 1 passed, 263 deselected, 35 warnings in 71.07s (0:01:11) ===========
```
``` …
```

test: introduced test_011_install_flows_same_match_diff_cookie

---

tests/test_e2e_15_mef_eline.py

Related to https://github.com/kytos-ng/mef_eline/pull/621/
Added a new e2e `test_006_evc_vlan_allocation_not_available`, it's passing, the rest of e2e tests are executing and I'll update here shortly too:
```
+ python3 -m pytest tests/test_e2e_15_mef_eline.py -k test_006_evc_vlan_allocation_not_available --reruns 2 -r fEr
collected 6 items / 5 deselected / 1 selected
tests/test_e2e_15_mef_eline.py .                                         [100%] …
```

test: added test_006_evc_vlan_allocation_not_available

---

tests/test_e2e_14_mef_eline.py

Closes #350 
Added tests where `failover_path` was expected to be different because of new disjointedness algorithm.
N/A
After change result:
```
+ python3 -m pytest tests/ -k test_030_EVC_path_disjointness --reruns 0 -r fEr
collected 281 items / 280 deselected / 1 selected
tests/test_e2e_14_mef_eline.py .                                         [100%]
```
Before change result, [branch](https://github.com/kytos-ng/mef_eline/compare/master...kytos-ng:mef_eline:regress/disjointness) (error expected):
```
+ python3 -m pytest tests/ -k test_030_EVC_path_disjointness --reruns 0 -r fEr …
```

Added test to expect lower disjointed path

---

tests/test_e2e_31_of_lldp.py

Closes #370 
Added test_010_liveness_intf_deletion
- New `test_010_liveness_intf_deletion` is passing (needs the related of_lldp and topology branches):
```
+ python3 -m pytest tests/ -k test_010_liveness_intf_deletion --reruns 2 -r fEr
collected 286 items / 285 deselected / 1 selected
tests/test_e2e_31_of_lldp.py .                                           [100%]
../../../../usr/local/lib/python3.11/dist-packages/kytos/core/config.py:254 …
```

tests: added `test_010_liveness_intf_deletion`

---

tests/test_e2e_20_flow_manager.py

Closes #372
Issue was caught when deleting flows as bulk and the switches had different flows. So added a similar case
This PR needs this `flow_manager` [PR](https://github.com/kytos-ng/flow_manager/pull/233).
N/A
Results from `fix/by_switch branch
```
+ python3 -m pytest tests/ -k test_110_install_delete_flows_by_switch_diff_cookie --reruns 0 -r fEr
collected 286 items / 285 deselected / 1 selected
tests/test_e2e_20_flow_manager.py .                                      [100%]
```
Results from master branch
```
tests/test_e2e_20_flow_manager.py F …
```

Added by_switch test with different cookies

---

tests/test_e2e_50_maintenance.py

Closes #380
Added tests similar to local tests from `maintenance` PR [#129](https://github.com/kytos-ng/maintenance/pull/129)
Base line with end time
```
{
"description": "MW1",
"start": "2025-10-15T14:50:00+0000",
"end": "2025-10-15T15:50:00+0000",
"interfaces": [
"00:00:00:00:00:00:00:02:3"
],
"force": true
}
```
No end time FAIL interferes with MW1
```
{
"description": "MW2",
"start": "2025-10-15T14:56:00+0000",
"end": null,
"interfaces": [
"00:00:00:00:00:00:00:02:3"
],
"force": true
}
```
No end time FAIL interferes with MW1 (even though it starts before MW1)
```
{
"description": "MW2",
"start": "2025-10-15T14:40:00+0000",
"end": null,
"interfaces": [
"00:00:00:00:00:00:00:02:3"
],
"force": true
}
```
No end time Success
```
{
"description": "MW3",
"start": …
```

Created test for no end time MWs

---

kytos-init.sh

Fix missing logging.ini file. kytosd needs to run before setting the logging level.
Closes #388

Update kytos-init.sh to fix issue 388
