kytos-ng/kytos-end-to-end-tests

- tests/test_e2e_05_topology.py
- Modifications following PEP8 style guide
- Unifying the testing to a common style (Pytest)
- Cleaning the code
- Modification on list_switches test structure
- Inclusion of setup and teardown methods to support a migration from Unittest to Pytest
- Elimination of the Unittest relationship
- Inclusion of fixtures to support the kytos restarting process
- Inclusion of test's descriptions
- Refactoring tests
> Unifying topology tests design

- tests/test_e2e_11_mef_eline.py
This pull request just add a wait time before checking the flow table after a LinkDown event on tests/test_e2e_11_mef_eline.py.
This will fix the following error on the end-to-end testing process:
```
______ TestE2EMefEline.test_on_primary_path_fail_should_migrate_to_backup ______
self = <tests.test_e2e_11_mef_eline.TestE2EMefEline testMethod=test_on_primary_path_fail_should_migrate_to_backup>
def test_on_primary_path_fail_should_migrate_to_backup(self):
""" When the primary_path is down and backup_path exists and is UP
the circuit will change from primary_path to backup_path. """
self.net.restart_kytos_clean()
time.sleep(10)
payload = {
"name": "my evc1",
"enabled": True,
"uni_a": {
"interface_id": "00:00:00:00:00:00:00:01:1",
"tag": {
"tag_type": 1,
"value": 101
}
},
"uni_z": { …
```
> Adjust end-to-end test 11 (mef_eline) to wait some time after the linkDown event

- tests/test_e2e_30_of_lldp.py
As discussed in kytos/of_lldp#62, the change polling interval API is not persistent. As so, this PR will change the end-to-end tests to skip the persistent check on it.
> Fix end-to-end tests for of_lldp - change polling interval API

- tests/test_e2e_12_mef_eline.py
The code currently uses features of string interpolation only available on python3.6+ (the tests are run under python2.7)
Fixes #16
> Fix string interpolation code style for python 2.7

- tests/test_e2e_05_topology.py
- tests/test_e2e_10_mef_eline.py
- tests/test_e2e_12_mef_eline.py
- tests/test_e2e_15_maintenance.py
- tests/test_e2e_20_flow_manager.py
- tests/test_e2e_21_flow_manager.py
- tests/test_e2e_30_of_lldp.py
It has been performed different task all over all the tests files, such as:
- Increasing the waiting time during the setup process
- Setting a Pytest environment with the setup_class & teardown_class approach
- Elimination of the Unittest relation
- Renaming methods to follow a logical and continuous sequence
- Cleaning up the code
- Following PEP8 convention
> Unifying all the tests to follow the same testing process approach

- tests/test_e2e_01_kytos_startup.py
This PR implements the log rotation routine to avoid errors being accounted for from the previous execution.
The end-to-end tests, especially tests/test_e2e_01_kytos_startup.py, verify if by the end of the test there are some errors on Kytos log (/var/log/syslog). However, if previous execution left an error, they will be accounted for in the current test - leading to an invalid assertion failure.
> Implement the log rotation routine

- tests/test_e2e_05_topology.py
This particular test requires that enable_all=True be used on the kytos controller startup.
> Adding enable_all=True in test_e2e_05_topology tests 400 and 500

- tests/test_e2e_21_flow_manager.py
Flow manager tests (tests/test_e2e_21_flow_manager.py) expect that all the entities are enable, but they aren't by default. This PR fix this issue and make all entities enabled by default.
> Apply flag enable_all in tests/test_e2e_21_flow_manager.py

- tests/test_e2e_12_mef_eline.py
It includes new tests to cover the missing API calls in the mef_eline NApp, such as:
- /v2/evc/ on GET
- /v2/evc/{circuit_id} on DELETE, and
- /v2/evc/schedule/ on GET (it was used /mef_eline/v2/evc/schedule/' + schedule_id on GET many times)
> mef-eline tests

- tests/helpers.py
- tests/test_e2e_10_mef_eline.py
- tests/test_e2e_11_mef_eline.py
This PR accomplishes two minor changes:
- Adjusting the topology names (DanielaTopo -> Ring4)
- create a dict of topology names to make them compatible with Mininet command line tool (mn):
```
mn --custom tests/helpers.py --topo ring --controller=remote,ip=127.0.0.1
```
> Adjust topology names and make them compatible with mn

- tests/test_e2e_10_mef_eline.py
The test is failing with the following error:
```
_______________________________ TestE2EMefEline.test_045_create_circuit_reusing_same_vlanid_from_previous_evc ________________________________
self = <tests.test_e2e_10_mef_eline.TestE2EMefEline instance at 0x7fb1d91bc2d8>
def test_045_create_circuit_reusing_same_vlanid_from_previous_evc(self):
payload = {
"name": "Vlan125_Test_evc1",
"enabled": True,
"dynamic_backup_path": True,
"uni_a": {
"interface_id": "00:00:00:00:00:00:00:01:1",
"tag": {"tag_type": 1, "value": 125}
},
"uni_z": {
"interface_id": "00:00:00:00:00:00:00:02:1",
"tag": {"tag_type": 1, "value": 125}
}
}
api_url = KYTOS_API + '/mef_eline/v2/evc/'
response = requests.post(api_url, data=json.dumps(payload), headers={'Content-type': 'application/json'})
assert …
```
> Fix mef_eline test to reuse the same vlan_id

- tests/test_e2e_10_mef_eline.py
- tests/test_e2e_15_maintenance.py
This PR will fix some errors on the testing code for maintenance napp (test the switch under maintenance):
- fix the definition of the primary_path (instead of interface_id it should be id)
- fix a misspelling on the switch id
- using variables to determine the sleeping time before and during the mw
> Fixing errors on test code for maintenance on switch

- tests/test_e2e_01_kytos_startup.py
- tests/test_e2e_05_topology.py
- tests/test_e2e_12_mef_eline.py
This PR includes two new tests relative to the Topology NApp to cover all the API calls.
The new implementations include:
- Implementation of new tests to verify the disabling process of all the interfaces on a switch as a persistent procedure.
API call /api/kytos/topology/v3/interfaces/switch/{dpid}/disable on Post
- Implementation of new tests to verify the API call '/topology/v3/' on Get
It also includes a minor modification on the method test_delete_circuit_id relative to the mef_eline NApp, in which the sleep time is increased to guarantee a proper response after deleting a circuit.
Some minor changes (code cosmetic related) are also included.
> New tests related to Topology Napp and some minor changes

- tests/test_e2e_20_flow_manager.py
- tests/test_e2e_30_of_lldp.py
- Flow_manager e2e tests do not use the enable_all=True option when restarting the controller, which makes many tests to fail
- Of_lldp e2e tests do not consider the last scheduled LLDP event using the old polling time, which makes the test to fail eventually
Examples of failures:
```
============================================================ test session starts =============================================================
platform linux2 -- Python 2.7.16, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /kytos-end-to-end-tests, inifile:
plugins: timeout-1.3.3
collected 61 items
tests/test_e2e_01_kytos_startup.py ..                                                                                                  [  3%]
tests/test_e2e_05_topology.py ................. …
```
> fix errors on flow_manager and of_lldp end-to-end-tests

- .gitignore
- tests/test_e2e_20_flow_manager.py
New tests to verify the NApp behavior against certain failures.
The commits include:
- Inclusion of pytest module to support the xfail actions
- New test to evaluate the flow status through the API's call after its installation
- New test to evaluate the behavior of the flow installation process on an unknown path
- New test to evaluate the behavior of the flow installation process specifying an empty payload (over different scenarios)
- New test to evaluate the behavior of the flow installation process specifying a wrong datatype payload
- New test to evaluate the behavior of the flow retrieving process of an unknown path
- New test to evaluate the behavior of the flow installation process specifying an empty payload (over different scenarios)
- New test to evaluate the behavior of the …
> New tests over the Flow manager

- tests/test_e2e_15_maintenance.py
- tests/test_e2e_30_of_lldp.py
The tests for of_lldp and maintenance sometimes fail and that could be due to the time.sleep(5) in the test. Since we are going to a standard of 10s after restarting the controller, I changed some tests to reflect that.
> Fix sleeps which were possible source of problems

- tests/test_e2e_15_maintenance.py
- tests/test_e2e_18_flow_manager.py
- tests/test_e2e_19_flow_manager.py
- tests/test_e2e_30_of_lldp.py
- Redistributing the file on test_e2e_20_flow_manager.py file into:
> test_e2e_18_flow_manager.py (regular/standard tests)
> test_e2e_19_flow_manager.py (failure tests)
**_leaving_**
> test_e2e_20_flow_manager.py` for (tricky tests)
- Adjustments on the sleep time
- Activating some test after PR inclusion
> Improvements over the code structure 

- tests/test_e2e_21_flow_manager.py
Currently, there is a test in flow_manage (`tests/test_e2e_21_flow_manager.py::TestE2EFlowManager::test_030_restart_kytos_should_preserve_flows`) which verifies if during kytos restart the flows are preserved. All the flows created by the user should be preserved, thus avoiding traffic disruption.
A especial case is the flows created by other kytos napps, such as of_lldp: since the flows are resubmitted every time the of_lldp napp is loaded, the flow_manage will send a FlowMod and the flow will be recreated. Since this especial case does not affect the user traffic, there is no risk in ignoring this behavior. The test was working before because when we restart kytos (tests/test_e2e_21_flow_manager.py L70) we leave all the switches disable (enable_all=False), then flow_manager will not …
> Fix test to verify preservation of flows during startup

- tests/test_e2e_15_maintenance.py
Improvements over the tests proposed to cover the maintenance Napp functionality. 
This contribution includes new tests to evaluate the performance of the new functionality related to the maintenance extension.
It also covers: 
- Specification of a circuit as a static method
- Fixing minor PEP8 style errors
- Renaming the methods to follow a logical order
- Reusing code relative to restart and create a circuit
- Extension of tests related to the patching process
> Tests improvement over the maintenance napp

- tests/helpers.py
- tests/test_e2e_10_mef_eline.py
This is related to the issue https://github.com/kytos-ng/topology/issues/11
When Kytos is restarted, the topology only loads the switches, interfaces and links from storehouse after all the switches reconnect. Thus, if you wanna delete an EVC on Kytos startup, you will have to wait until the switches to connect, then mef_eline is able to load the EVCs and only then you can finally delete the EVC.
This PR adds a new test to evaluate this behavior. Since there is a PR already opened and under review to fix this issue (the PR's patch was already applied on the Kytos amlight docker image), I didn't add the pytest xfail decorator.
> Add new test to mef_eline delete when no switches are connected

- tests/test_e2e_10_mef_eline.py
This PR fixes some syntactic errors introduced on the latest test related to mef_eline Napp
> Fix syntax error on mef_eline 10 test 070

- tests/test_e2e_15_maintenance.py
This PR removes all the xfailing routines activating all the maintenance tests and monitoring processes.
> Removing the xfailing routines in order to activate the latest tests

- tests/test_e2e_15_maintenance.py
This PR includes new implementations relative to the maintenance NApp, including:
- The inclusion of a new test to verify the ending process of a running maintenance
- The fixes of the return error 200 --> 201 on Patch, following design structure on changes via API call
- The fixes of the payloads tagging and tests method naming structure given the new contributions
> New contributions on maintenance NApp

- tests/test_e2e_15_maintenance.py
The new contribution enforces a strict correlation between actions and their return codes for all the cases evaluated, such as:
- It is fixed the patching action on '/maintenance/{mw_id},' returning 200 in case of success.
- It is fixed the patching action on '/maintenance/{mw_id}/end,' returning 200 in case of success.
- It is fixed the patching action on '/maintenance/{mw_id}/extend,' returning 200 in case of success.
N/A
> It fixes patching actions return codes.

- tests/helpers.py
This PR adds AmLight's topology to `test/helper.py`, to enable running tests with more complex topologies.
> Add AmLight topology to helpers

- tests/test_e2e_14_mef_eline.py
kytos-ng/mef_eline has an issue that returns an incorrect path when the user requests an EVC which the UNI is actually an NNI. This PR will add a test to validate this behavior leveraging the new/complex AmLight topology.
> Add test to validate mef_eline issue 72

- tests/test_e2e_10_mef_eline.py
This PR fixes a minor issue on the order which the backup path was specified in the payload. Since the kytos core mandates the order of the NNIs in a Link object, this PR fixes the payload to match the expected order.
> Fix order of links in backup_path for test mef_eline_11 / test_135_patch_backup_path

- tests/test_e2e_15_maintenance.py
Fixes #105 
This PR adds a few more seconds before submitting a circuit creation, to give kytos enough timer to discovery links.
> Increate wait time before submit circuit creation

- tests/test_e2e_10_mef_eline.py
This PR adds a new sleep into `tests/test_e2e_10_mef_eline.py::TestE2EMefEline:: test_085_create_and_remove_ten_circuit_concurrently` to fix borderline cases where the flows were just submitted and Kytos didnt have enough time to create the actual flows.
> Fix test for mef_eline by adding the proper wait time

- tests/test_e2e_10_mef_eline.py
This PR just adds a few assertions on the return code of `/api/kytos/mef_eline/v2/evc/{evc_id}/metadata` API to help to troubleshoot in case of failure (such as what we are seeing in kytos-ng/mef_eline#130).
> Add extra assertions to help troubleshooting

- tests/test_e2e_01_kytos_startup.py
- tests/test_e2e_05_topology.py
- tests/test_e2e_10_mef_eline.py
- tests/test_e2e_11_mef_eline.py
- tests/test_e2e_12_mef_eline.py
- tests/test_e2e_13_mef_eline.py
- tests/test_e2e_15_maintenance.py
- tests/test_e2e_20_flow_manager.py
- tests/test_e2e_21_flow_manager.py
- tests/test_e2e_22_flow_manager.py
- tests/test_e2e_23_flow_manager.py
- tests/test_e2e_30_of_lldp.py
This PR adds more information to assertions on request/status_code: it adds the response.text. The response.text is quite useful because it may contains more information on why the result is different from what was expected.
> Add response.text to all assertions on request status code

- tests/helpers.py
Fixes #112 
This PR adds a way to force Kytos to stop if the shutdown process still leaves the PID file after 5s of shutdown being requested.
> Add way to force stop Kytos after 5s

- kytos-init.sh
- tests/conftest.py
This PR adds a few options/configs that we also apply in the CI/CD pipeline. Thus, when running the tests outside of the CI/CD environment one can get the same behavior.
Also, I've added a pytest hook to print start and end time for failed tests. This helps troubleshooting by matching the log entries from the specific time interval of the failed test.
> Sync kytos-init.sh as we have in the CI pipeline and add more info to help troubleshoot

- README.rst
- kytos-init.sh
Updated the `python` command to explicitly call `python3`, it turns out on Debian bullseye based on this PR that's under code review https://github.com/amlight/kytos-docker/pull/9, the base image also doesn't have `python` pointing to `python3`, so I figured explicitly would also keep it backwards compatible, and some distros traditionally use `python` as  Python 2.7 as well:
```
root@127bf29458f7:/#
root@127bf29458f7:/#
root@127bf29458f7:/# python
bash: python: command not found
root@127bf29458f7:/# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
> [Feature] Updated to use `python3` executable to be compatible with debian_bullseye

- tests/test_e2e_01_kytos_startup.py
This is something to augment for debugging when this fails like it has happend recently, so now, when there's errors or warnings we should see something like this: 
```
>           assert re.findall(r'kytos.*?(error|exception)(.*)?', f.read(), re.I) == []
E           assert [('ERROR', ' ...","name":"N')] == []
E             Left contains one more item: ('ERROR', ' main:167:  Failed to push flows on 00:00:00:00:00:00:00:01, error: {"code":404,"description":"switch is disabled.","name":"N')
E             Use -v to get the full diff
```
Before it used to be like this:
```
def test_start_kytos_without_errors(self):
with open('/var/log/syslog', "r") as f:
>           assert re.findall('kytos.*(error|exception)', f.read(), re.I) == []
E           AssertionError: assert ['Error', 'Error'] == [] …
```
> [Fix] `findall` to also capture msg 

- kytos-init.sh
The extra logging `2>&1 | tee log-e2e-$(date +%Y%m%d%H%M%S)` was left by accident and it is not necessary as part of the testing script. In fact, the extra logging will mislead to successful execution of the script and leads to pipeline passing even when Pytest fails.
> Update Kytos-init.sh to remove the log-e2e-date file

- kytos-init.sh
This PR will disable Napps amlight/sdntrace and amlight/sdntrace-cp (along with their dependencies) to workaround issue #110. Those Napps used to be disabled in the docker image `amlight/kytos:latest` but they will be enabled by default as soon as amlight/kytos-docker#10 lands.
> Disable sdntrace and sdntrace-cp before running tests

- tests/test_e2e_23_flow_manager.py
Fixes #127
I've replaced the `subprocess` parallel exec with a `ThreadPoolExecutor` and `Futures` in order to make easier to wait for the results, since threads are lighter and easier to wait for, this patch should make this test case less flaky, at least when it comes down to make sure all requests succeeded (there's still another time/wait dependency when waiting for the flow to be there, but that part is relatively stable as of now, so no changes in that part). Lately, this test case hasn't failed that many times on GitLab CI though. 
```
diff --git a/kytos-init.sh b/kytos-init.sh
index 9cbe0df..fc3d0ad 100755
--- a/kytos-init.sh
+++ b/kytos-init.sh
@@ -22,6 +22,11 @@ sed -i 's/WARNING/INFO/g' /etc/kytos/logging.ini
test -z "$TESTS" && TESTS=tests/
python3 scripts/wait_for_mongo.py …
```
> [Fix] Make TestE2EFlowManager::test_065_install_flow less flaky

- README.rst
- tests/helpers.py
- tests/test_e2e_01_kytos_startup.py
- Adapted startup tests not to expect storehouse on `/core/napps_enabled/`
> Adapted startup tests not to expect storehouse on `/core/napps_enabled/`

- kytos-init.sh
- tests/helpers.py
- tests/test_e2e_31_of_lldp_loop_detection.py
- tests/test_e2e_32_of_lldp.py
Fixes #125
Added TestE2EOfLLDPLoopDetection to test that given a looped topology, it is going to disable the interface, unless it is an ignored loop.
This PR depends on this branch of_lldp https://github.com/kytos-ng/of_lldp/pull/36.
I run the e2e test and it's passing:
+ python3 -m pytest tests/test_e2e_32_of_lldp.py
collected 3 items
tests/test_e2e_32_of_lldp.py ...                                         [100%]
================== 3 passed, 22 warnings in 95.88s (0:01:35) ===================
> [Feature] Added e2e test for LLDP loop_detection disable action

- tests/test_e2e_15_maintenance.py
Fixes #138 
The test passes by increasing the waiting time in the test from 3 to 4 seconds. So, the test failure is solved by increasing the time to give Kytos more time to redeploy the EVC.
I repeated the test 10 times and it passed every time:
================== 1 passed, 34 warnings in 139.33s (0:02:19) ==================
+ for i in {1..10}
+ echo 'testing iteration 9'
testing iteration 9
+ python3 -m pytest tests/test_e2e_15_maintenance.py::TestE2EMaintenance::test_085_end_running_mw_on_switch
tests/test_e2e_15_maintenance.py .                                       [100%] …
> Increasing wait time in test_085_end_running_mw_on_switch e2e_15

- kytos-init.sh
I'm setting this new `CONSISTENCY_MIN_VERDICT_INTERVAL` that's being introduced on this PR https://github.com/kytos-ng/flow_manager/pull/105. 
The consistency check has this granular interval control now (please read the PR description for a better understanding), although is still driven by the flow stats being received. This new value being set is still compatible with how the e2e tests were written with `STATS_INTERVAL=3` assuming that it would start running around that interval.
> Set consistency_min_verdict_interval for new changes

- tests/test_e2e_10_mef_eline.py
This PR is related to kytos-ng/mef_eline#175
With the introduction of the failover path on fully dynamic EVCs (those in which `dynamic_backup_path = True and not primary_path and not backup_path`), the number of flows in the flow table grew a bit. Thus, some end-to-end tests had to be adjusted accordingly.
The basic idea of the failover path is described in EP029, but below is the important part that impacts this PR:
> Let's take Topology 1 as the first example. Suppose that the best path will be set up to S - X - W - D. The maximum disjoint path (to be used as a failover path) will be set up to S - Z - W - I - D. The following OpenFlow rules will be created before a link failure:
> 
> OpenFlow rules for the primary path:
> - h1 -> S -> X -> W -> D -> h2
> - h2 -> D -> W -> X -> S -> h1
> …
> [Fix] Adjust MEF E-Line tests to also consider failover_path flows

- tests/test_e2e_15_maintenance.py
Fixes #145
This PR is on topf of PR #147 
The test case looks good, I've explored it, looks like it's a convergence issue, where a flow hasn't been deleted yet in the switch, no false positives or consistency check reinstalling them though. I've slightly increase the sleep to have an extra time before checking the flows, that should suffice, I believe, I've run 5 iterations locally:
```
root@be0714fb5efc:/# cat script.sh
#!/bin/bash
for i in {1..5}
do
echo "Running iteration $i..."
python3 -m pytest tests/ --timeout=360 -k test_010_create_mw_on_switch_should_move_evc
sleep 10
done
root@be0714fb5efc:/# grep -i "consistency" /var/log/messages
============================================================== 1 passed, 198 deselected, 34 warnings in 226.82s (0:03:46) …
```
> [Fix] MW flaky test case

- tests/test_e2e_10_mef_eline.py
- tests/test_e2e_11_mef_eline.py
- tests/test_e2e_12_mef_eline.py
- tests/test_e2e_15_maintenance.py
- tests/test_e2e_20_flow_manager.py
- tests/test_e2e_21_flow_manager.py
- tests/test_e2e_23_flow_manager.py
- tests/test_e2e_31_of_lldp.py
Fixes #150 
- Included dump-flows str in asserts that are comparing the length
So, now if it fails you should get an assertion with more context to figure out why it failed:
```
>       assert len(flows_s1.split('\r\n ')) == BASIC_FLOWS + 1, flows_s1
E       AssertionError:  cookie=0x0, duration=97.948s, table=0, n_packets=0, n_bytes=0, priority=50000,dl_src=ee:ee:ee:ee:ee:03 actions=CONTROLLER:65535
E          cookie=0x0, duration=97.943s, table=0, n_packets=0, n_bytes=0, priority=50000,dl_src=ee:ee:ee:ee:ee:02 actions=CONTROLLER:65535
E          cookie=0xaaa35c0d3d2c814a, duration=15.343s, table=0, n_packets=0, n_bytes=0, in_port="s1-eth1",dl_vlan=100 actions=mod_vlan_vid:100,mod_vlan_vid:3537,output:"s1-eth4"
E          cookie=0xaaa35c0d3d2c814a, duration=15.342s, table=0, n_packets=0, …
```
> Included dump-flows str in asserts that are comparing the length

- tests/test_e2e_15_maintenance.py
This should use the new endpoints introduced with kytos-ng/maintenance#60, resolving #157. I haven't been able to directly test this, as this project currently doesn't provide a method to use a local copy of an NApp or pull a version from a specific branch.
> Updated maintenance tests to use new endpoints.

- tests/test_e2e_01_kytos_startup.py
Fixed `test_start_kytos_api_core` test case, removed scheduler from the expected list:
```
+ python3 -m pytest tests/ -k test_start_kytos_api_core
collected 199 items / 198 deselected / 1 selected
tests/test_e2e_01_kytos_startup.py .                                     [100%]
test_e2e_01_kytos_startup.py: 17 warnings …
```
> [Fix] `test_start_kytos_api_core` test case, removed scheduler from the expected list

- tests/test_e2e_10_mef_eline.py
Fixes #161 
```
+ python3 -m pytest tests/ -k test_115_patch_priority
collected 199 items / 198 deselected / 1 selected
test_e2e_10_mef_eline.py: 17 warnings
test_e2e_10_mef_eline.py: 17 warnings
/usr/lib/python3/dist-packages/mininet/node.py:1122: …
```
> Updated mef_eline priority as sb_priority

- tests/test_e2e_15_mef_eline.py
Fixes #165 
In the future, we'll have more test cases potentially covering [AmLight topo](https://github.com/amlight/kytos-end-to-end-tests/blob/master/kytos-amlight-topo-init.sh), for now I've added a minimum regression test case until we also stabilize the rest of false positives that sometimes happen. 
Local test with `branch_mef_eline=feature/pathfinder_cspf` and `branch_pathfinder=fix/links_filter_2`
```
+ python3 -m pytest tests/ -k e2e_15_mef_eline
collected 200 items / 199 deselected / 1 selected
tests/test_e2e_15_mef_eline.py .                                         [100%] …
```
> Added e2e test for mef_eline with primary and secondary constraints

- tests/test_e2e_10_mef_eline.py
Updated `test_030_create_evc_tag_notag` to avoid false positive, it turns out that `assert 'dl_vlan=104' not in flows_s2` could unintentionally match an uplink random dl_vlan such as 1043, so I've updated the assert to be more specific to avoid this false positive:
```
>       assert 'dl_vlan=104' not in flows_s2
E       assert 'dl_vlan=104' not in ' cookie=0x0...ER:65535\r\n'
E         'dl_vlan=104' is contained here:
E           "s2-eth3",dl_vlan=1043 actions=strip_vlan,output:"s2-eth1"
E         ?           +++++++++++
E            cookie=0xab00000000000002, duration=21.814s, table=0, n_packets=14, n_bytes=588, priority=1000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535
```
I've re-run it locally with this branch, it's passing:
``` …
```
> Updated `test_030_create_evc_tag_notag` to avoid false positive

- tests/test_e2e_10_mef_eline.py
Enhanced #160, this is on top of PR #170 
As highlighted on this comment https://github.com/amlight/kytos-end-to-end-tests/issues/160#issuecomment-1278151550, this fix here won't completely mitigate the issue, but I took the opportunity to slightly increase a sleep there and also to make an assert stricter, I ran it locally three times, let's keep an eye on this one:
```
+ for i in {1..3}
+ echo 'iteration 3'
iteration 3
+ python3 -m pytest -s -vv --timeout=300 tests/ -k test_025_create_evc_different_tags_each_side
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
timeout: 300.0s …
```
> Slightly increase a sleep and also updated an assert to match stricter

- kytos-init.sh
- tests/helpers.py
- tests/test_e2e_20_flow_manager.py
- tests/test_e2e_21_flow_manager.py
- tests/test_e2e_23_flow_manager.py
Fixes #172 
- Increased `CONSISTENCY_MIN_VERDICT_INTERVAL` to 60 (this is the half the value we have by default), so the consistency check, after an OF handshake will only kick in after this interval at least, so this helps out to avoid having premature consistency check runs that would lead to slower convergence and false positive asserts during convergence (if we have any asserts going on during convergence).
- Increased `STATS_INTERVAL` to 30 to minimize the overhead of FlowStats messages and decrease a bit of IO/CPU on OvS instances. This interval was initially low intentionally to avoid waiting too much for flows to be installed again and trigger the consistency check. Since the consistency check is triggered after the initial handshake/flow stats reply …
> Increased `CONSISTENCY_MIN_VERDICT_INTERVAL` and adapted tests

- kytos-init.sh
- tests/conftest.py
Fixes #185
This is on top of PR #178 
- Hooked `pytest-rerunfailures` 
- Updated `pytest_terminal_summary` to also report reruns as shown here, same approach that Italo has contributed to help out to identify start and stop times, https://github.com/amlight/kytos-end-to-end-tests/pull/178#issuecomment-1315837807 to help us out when analyzing failures (check this comment/thread out for more context)
If you're running locally and creating new tests that aren't stable yet you can zero the RERUN var. By default, it'll try to rerun.
> [Feat] Hooked `pytest-rerunfailures` 

- kytos-amlight-topo-init.sh
This PR will add some interfaces that are missing for JAX2 switch from AmLight topo (`test/helpers.py`) in the `kytos-amlight-topo-init.sh`.
Without those interfaces, some links will never come up and the init script will fail.
This script is only used for manual tests, so no impact is expected.
> Adding interfaces for JAX2 in the init script

- kytos-init.sh
- tests/helpers.py
Fixes #188 
Fixes #189 
- Updated reconnect_switches to avoid deleting the OvS controller config
- Decreased STATS_INTERVAL to 7, since on PR https://github.com/amlight/kytos-end-to-end-tests/pull/178, I mostly decreased it to minimize IO overhead, using 7 it still with the most time.sleep(10) even after a forced OF reconnection/handshake that we have since the max interval to request flow stats [is upper bound to `% STATS_INTERVAL/2`](https://github.com/kytos-ng/of_core/blob/master/main.py#L92) depending on the size of the topology
I locally explored with the test `test_040_replace_action_flow` that @italovalcy reported:
```
+ sed -i 's/STATS_INTERVAL = 60/STATS_INTERVAL = 7/g' /var/lib/kytos/napps/kytos/of_core/settings.py
+ sed -i 's/CONSISTENCY_MIN_VERDICT_INTERVAL …
```
> [Fix] Fixed reconnect switches side effect and decreased `STATS_INTERVAL`

- tests/test_e2e_10_mef_eline.py
- Fix test_125_patch_dynamic_backup_path for PR https://github.com/kytos-ng/mef_eline/pull/233, if `dynamic_backup_path` is false then it should have a `primary_path` set
I've tested it locally with `mef_eline` PR 233 (link mentioned above)
```
+ python3 -m pytest --timeout=600 tests/ -k test_125_patch_dynamic_backup_path
plugins: rerunfailures-10.2, timeout-2.1.0
timeout: 600.0s
collected 199 items / 198 deselected / 1 selected …
```
> [fix] test_125_patch_dynamic_backup_path for mef_eline PR 233

- kytos-init.sh
- tests/test_e2e_40_sdntrace.py
Fix #174 
Add `test_e2e_40_sdntrace.py::TestE2ESDNTrace::test_030_run_sdntrace_for_stored_flows` to test how the traces are obtained from flow_manager stored_flow.
Also, `test_e2e_40_sdntrace.py::TestE2ESDNTrace::test_001_run_sdntrace_cp` hass passed.
> Add test for get stored flows from flow_manager

- tests/test_e2e_15_mef_eline.py
Related to issue from `mef_eline` [#249](https://github.com/kytos-ng/mef_eline/issues/249)
Changed test `test_001_create_update_with_constraints()` from `test_e2e_15_mef_eline.py` to comply with changes made on `mef_eline` PR [#254](https://github.com/kytos-ng/mef_eline/pull/254)
```
tests/test_e2e_15_mef_eline.py .                                         [100%]
```
> Updated tests from mef_eline

- tests/test_e2e_20_flow_manager.py
Closes #205 
Related to https://github.com/kytos-ng/of_core/issues/102
Added `test_016_install_invalid_flow_cookie_overflowed`. `flow_manager` still hasn't complete implemented API spec validation, but this was a case where it ended hitting a problem in `msg_out` queue so we're adding this as a regression test. In the future, more validation tests should be planned for
This individual test is passing building with the branches that it depends on https://github.com/kytos-ng/flow_manager/pull/137
```
+ python3 -m pytest tests/ --timeout=600 -k test_016_install_invalid_flow_cookie_overflowed
timeout: …
```
> test: added test_016_install_invalid_flow_cookie_overflowed

- tests/test_e2e_40_sdntrace.py
This is related to PR https://github.com/kytos-ng/sdntrace_cp/pull/75.
`test_030_run_sdntrace_for_stored_flows` has been updated, as the response of `/traces` has been changed.
The response is verified to be a list with the same number of elements as the number of requests.
In addition, some cases are checked in which the response must be an empty list and a case in which a complete trace must be returned.
+ python3 -m pytest tests/test_e2e_40_sdntrace.py
collected 4 items
tests/test_e2e_40_sdntrace.py ....                                       [100%]
=============================== warnings …
> fix: update for change in the response of /traces

- tests/test_e2e_20_flow_manager.py
Related to a PR in [flow_manager](https://github.com/kytos-ng/flow_manager/pull/140)
Add a test to check that `/flow_manager/v2/stored_flows` returns flows that are sorted in descending order by `priority`. 
+ python3 -m pytest tests/test_e2e_20_flow_manager.py::TestE2EFlowManager::test_017_install_flows_and_retrieve_sorted
tests/test_e2e_20_flow_manager.py .                                      [100%]
test_e2e_20_flow_manager.py: 17 warnings
/usr/lib/python3/dist-packages/mininet/node.py:1121: …
> feature: Added a test to check that the order of the requested stored flows is descending

- tests/test_e2e_40_sdntrace.py
Related to PR [73 in sdntrace_cp](https://github.com/kytos-ng/sdntrace_cp/pull/73) 
Update tests related to the changes in `sdntrace_cp` to add the `loop` and `incomplete` types.
Note that in all the failed traces there is now one more item with the type `incomplete`.
- When before it was `[]`. now it is a list that contains one item with type `incomplete`.
- When before it was an array with `x` items, now it is an array containing `x+1` items, and the type of the last one is `incomplete`.
+ python3 -m pytest tests/test_e2e_40_sdntrace.py
collected 6 items
tests/test_e2e_40_sdntrace.py ...... …
> feature: Test new trace types

- tests/test_e2e_40_sdntrace.py
Related to [PR 81 in sdntrace_cp](https://github.com/kytos-ng/sdntrace_cp/pull/81)
Add `tests/test_e2e_40_sdntrace.py::TestE2ESDNTrace::test_055_run_sdntrace_loop` to check that a loop is detected when the input and outgoing interfaces match in a trace.
tests/test_e2e_40_sdntrace.py ........                                   [100%]
/usr/lib/python3/dist-packages/mininet/node.py:1122: DeprecationWarning: distutils Version classes are deprecated. Use …
> Test new cases of loop in /traces

- tests/test_e2e_10_mef_eline.py
Related to [mef_eline](https://github.com/kytos-ng/mef_eline/pull/258)  PR
Tests including the recent addition to `vlan` available values `untagged` and `any`.
```
+ python3 -m pytest tests/test_e2e_10_mef_eline.py -k '160 or 165 or 170 or 175 or 180 or 185 or 190 or 195 or 200 or 205' --reruns 2 -r fEr
collected 39 items / 29 deselected / 10 selected
tests/test_e2e_10_mef_eline.py ..........                                [100%]
```
> Added tests for untagged and any from mef_eline changes

- tests/test_e2e_11_mef_eline.py
Closes #217 
Added and augmented test to cover bad request response format since `@validate` decorator implementation will change and is being moved.
```
+ python3 -m pytest tests/ -k test_025_should_fail_due_to_invalid_attribute_on_payload
collected 224 items / 223 deselected / 1 selected
tests/test_e2e_11_mef_eline.py .                                         [100%]
------------------------------- start/stop times -------------------------------
========== 1 passed, 223 deselected, 51 warnings in 79.56s (0:01:19) ===========
+ python3 -m pytest tests/ -k test_026_validate_bad_request_response_format …
```
> test: Added test_026_validate_bad_request_response_format

- tests/test_e2e_10_mef_eline.py
- tests/test_e2e_40_sdntrace.py
Related to [PR of `mef_eline`](https://github.com/kytos-ng/mef_eline/pull/303)
Add `test_250_run_bulk_sdntraces_any_vlan` and `test_255_run_bulk_sdntraces_untagged_vlan` to test the `untagged` and `any` cases for `vlan` in `mef_eline`.
```
+ python3 -m pytest tests/test_e2e_10_mef_eline.py::TestE2EMefEline::test_250_run_bulk_sdntraces_any_vlan
test_e2e_10_mef_eline.py: 17 warnings …
```
> Test `untagged` and `any` values for `vlan` in `mef_eline`

- tests/test_e2e_40_sdntrace.py
Related to [PR of `sdntrace_cp`](https://github.com/kytos-ng/sdntrace_cp/pull/82)
Add `test_070_run_sdntrace_untagged_vlan` and `test_075_run_sdntrace_any_vlan` to test the `untagged` and `any` cases for `vlan` in `sdntrace_cp`.
+ python3 -m pytest tests/test_e2e_40_sdntrace.py
collected 10 items
tests/test_e2e_40_sdntrace.py ..........                                 [100%]
/usr/lib/python3/dist-packages/mininet/node.py:1121: DeprecationWarning: distutils Version classes are …
> Test `untagged` and `any` values for vlan in sdntrace_cp

- tests/test_e2e_40_sdntrace.py
Related to [PR of sdntrace_cp](https://github.com/kytos-ng/sdntrace_cp/pull/85)
Add test_080_validate_attribute_on_payload to test that `/traces` validates payload.
+ python3 -m pytest tests/test_e2e_40_sdntrace.py::TestE2ESDNTrace::test_080_validate_attribute_on_payload
tests/test_e2e_40_sdntrace.py .                                          [100%]
/usr/lib/python3/dist-packages/mininet/node.py:1121: DeprecationWarning: distutils Version classes are …
>  `/traces` validates payload

- tests/test_e2e_40_sdntrace.py
Closes #221 
`tests/test_e2e_40_sdntrace.py::TestE2ESDNTrace::test_070_run_sdntrace_untagged_vlan` failed when trying to create an existing evc. Note that a different evc is now created.
+ python3 -m pytest tests/test_e2e_40_sdntrace.py
collected 11 items
tests/test_e2e_40_sdntrace.py ...........                                [100%] …
> Fix issue on duplicated evc

- tests/test_e2e_40_sdntrace.py
Closes #225 
e2e `test_070_run_sdntrace_untagged_vlan` fails when the evc it tries to create exists. To prevent this test from failing, it checks not only that the evc was created, but also whether it already exists. So, in these two cases `/traces` is called.
tests/test_e2e_40_sdntrace.py ...........                                [100%]
/usr/lib/python3/dist-packages/mininet/node.py:1122: DeprecationWarning: distutils Version classes are deprecated. …
> Fix: e2e `test_070_run_sdntrace_untagged_vlan`

- tests/test_e2e_13_mef_eline.py
Closes #224 
- Skipped certain `xfail` tests that are causing tracebacks for now, which are just false positive noise in the logs. Once validations are in place then this will be reverted (I'll map another issue shortly for this)
I made sure that of the tests was properly skipped
```
Ran 'hello' command on MongoDB successfully. It's ready!
+ python3 -m pytest tests/ -k test_035_patch_an_inconsistent_uni_a
collected 227 items / 226 deselected / 1 selected
tests/test_e2e_13_mef_eline.py s                                         [100%]
=============================== warnings summary …
```
> test: skip certain `xfail` tests that are causing tracebacks for now

- tests/test_e2e_40_sdntrace.py
Related to [PR of sdntrace_cp](https://github.com/kytos-ng/sdntrace_cp/pull/93)
Add `v1` on routes of `sdntrace_cp`
```
tests/test_e2e_40_sdntrace.py ...........                                [100%]
/usr/lib/python3/dist-packages/mininet/node.py:1122: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
StrictVersion( '1.10' ) )
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html …
```
> Update for `v1` in routes of `sdntrace_cp`

- tests/test_e2e_13_mef_eline.py
Closes #231 
`xfail` marks are no longer needed since these tests are passing.
```
+ python3 -m pytest tests/test_e2e_13_mef_eline.py -k '090 or 040' --reruns 2 -r fEr
collected 44 items / 42 deselected / 2 selected
tests/test_e2e_13_mef_eline.py ..                                        [100%]
```
> Removed xfail for 040 and 090 tests

- tests/test_e2e_10_mef_eline.py
- tests/test_e2e_11_mef_eline.py
- tests/test_e2e_12_mef_eline.py
- tests/test_e2e_32_of_lldp.py
- tests/test_e2e_40_sdntrace.py
- tests/test_e2e_50_maintenance.py
Closes #236 
- I've also adapted some 4XX status code accordingly.
- Reran all test suites 4 times with this branch and all `starlette` PRs related that are in code review:
```
collected 227 items
tests/test_e2e_05_topology.py ..................                         [  8%]
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 26%]
tests/test_e2e_11_mef_eline.py ...... …
```
> chore: fix routes trailing slashes inconsistencies to avoid validation errors

- tests/test_e2e_40_sdntrace.py
Closes https://github.com/kytos-ng/sdntrace/issues/43
This needs `sdntrace`'s PR https://github.com/kytos-ng/sdntrace/pull/52
- Augmented sdntrace_cp test case to also run sdntrace for untagged/any EVC
- Ideally, these should've been done in a different test case, but we have technical debt how EVCs are being created, which needs to be handled first on https://github.com/kytos-ng/kytos-end-to-end-tests/issues/239, once that's fixed then theses ones here should be moved too.
I've dispatched e2e on GitLab:
```
+ python3 -m pytest tests -k 40_sdntrace --reruns 2 -r fEr
plugins: …
```
> test: augmented sdntrace_cp test case to also run sdntrace for untagged/any EVC

- tests/test_e2e_01_kytos_startup.py
- tests/test_e2e_70_kytos_stats.py
Closes #235 
Add e2e tests for `kytos_stats` endpoints including the new endpoint `v1/table/stats` to request tables.
N/A
N/A
> Add e2e tests for `kytos_stats`

- tests/test_e2e_50_maintenance.py
This fixes a minor bug in the maintenance end-to-end tests, where a few tests were attempting to create maintenance windows with incorrect switch ids. The issue associated was discovered when testing kytos-ng/maintenance#78, which adds in a validation step to check if all items in a maintenance window exist.
Here are the results for the end-to-end tests with kytos-ng/maintenance#78.
```
kytos-end-to-end-tests-kytos-1  | Starting enhanced syslogd: rsyslogd.
kytos-end-to-end-tests-kytos-1  | /etc/openvswitch/conf.db does not exist ... (warning).
kytos-end-to-end-tests-kytos-1  | Creating empty database /etc/openvswitch/conf.db.
kytos-end-to-end-tests-kytos-1  | Starting ovsdb-server.
kytos-end-to-end-tests-kytos-1  | Configuring Open vSwitch system IDs.
kytos-end-to-end-tests-kytos-1  | …
```
> Fix bad switch ids in maintenance tests

- tests/test_e2e_15_mef_eline.py
Related to https://github.com/kytos-ng/mef_eline/pull/355 (if fixes the e2e failing test there)
Now `spf_attribute` is only stored if it's been set, so I had to adapt this test case accordingly. 
```
+ python3 -m pytest tests -k test_001_create_update_with_constraints --reruns 2 -r fEr
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.2.0
collected 239 items / 238 deselected / 1 selected
tests/test_e2e_15_mef_eline.py .                                         [100%]
========== 1 passed, 238 …
```
> fix: adapted expected spf_attribute value

- tests/test_e2e_60_of_multi_table.py
Closes #249 
Fixed error because `of_lldp` changed its priority to `50000`. It having the same priority as `coloring` makes the order no deterministic
> Fixed test_005_enable_pipeline()

- tests/test_e2e_31_of_lldp.py
Closes #248
This raises the priority of the flow intended to drop lldp packets in `test_005_liveness_goes_down`.
When running tests on `test_e2e_31_of_lldp.py` the results are:
```
kytos-end-to-end-tests-kytos-1  | Starting enhanced syslogd: rsyslogd.
kytos-end-to-end-tests-kytos-1  | /etc/openvswitch/conf.db does not exist ... (warning).
kytos-end-to-end-tests-kytos-1  | Creating empty database /etc/openvswitch/conf.db.
kytos-end-to-end-tests-kytos-1  | Starting ovsdb-server.
kytos-end-to-end-tests-kytos-1  | Configuring Open vSwitch system IDs.
kytos-end-to-end-tests-kytos-1  | Starting ovs-vswitchd.
kytos-end-to-end-tests-kytos-1  | Enabling remote OVSDB managers.
kytos-end-to-end-tests-kytos-1  | + sed -i 's/STATS_INTERVAL = 60/STATS_INTERVAL = 7/g' …
```
> Fix priority in of_lldp tests

- tests/test_e2e_40_sdntrace.py
Closes #239 
This is to remove the circuits with `teardown_method` to avoid the error HTTP 409 The EVC already exists in the test suite `TestE2ESDNTrace`.
> Remove circuits to avoid HTTP 409.

- tests/test_e2e_70_kytos_stats.py
Closes #243 
Add `test_036_table_1_active_count_update` test to create some traffic on table 1, and  make sure that the stats are accurate.
Update `test_015_packet_count` and `test_020_bytes_count` tests to avoid trying to find a non-empty flow, instead a flow is installed and query it later for stats.
> Enhance `kytos_stats`

- tests/test_e2e_10_mef_eline.py
- tests/test_e2e_11_mef_eline.py
- tests/test_e2e_12_mef_eline.py
- tests/test_e2e_13_mef_eline.py
- tests/test_e2e_14_mef_eline.py
- tests/test_e2e_15_mef_eline.py
- tests/test_e2e_40_sdntrace.py
- tests/test_e2e_50_maintenance.py
- tests/test_e2e_60_of_multi_table.py
- tests/test_e2e_70_kytos_stats.py
Closes #260 
Tag-type is changed to string
```
VLAN = 1 to  'vlan'
VLAN_QINQ = 2 to 'vlan_qinq'
MPLS = 3 to 'mpls'
```
Update: This change is no longer necessary but it is better to be changing to a string instead of sticking with an integer type value.
> fix: changed tag_type to string

- tests/test_e2e_80_pathfinder.py
Closes #202 
Added tests for pathfinder
```
timeout: 60.0s
collected 8 items
```
> Pathfinder e2e Test

- tests/test_e2e_15_mef_eline.py
- tests/test_e2e_40_sdntrace.py
Closes #267 
Added test for `vlan_range` epic:
- Create a circuit with vlan as range
- Patch partial update to circuit.
- Patch fail for different vlan
- Check multiple flows for created circuit
- Check pings with random values within the masks
- Check traces with random values within the masks
```
+ python3 -m pytest tests/ -k 'test_005_evc_vlan_range or test_100_trace_circuit_vlan_range' --reruns 0 -r fEr
plugins: timeout-2.1.0, rerunfailures-10.2, anyio-3.6.2
collected 254 items / 252 deselected / 2 selected
tests/test_e2e_15_mef_eline.py .                                         [ 50%]
tests/test_e2e_40_sdntrace.py . …
```
> Added test for vlan_range

- tests/test_e2e_80_pathfinder.py
This doesn't cl0se issue #269, but until it's fully addressed/analyzed it'll skip this test case
I confirmed it's skipping `test_10_undesired_link_and_max_path`
```
[vx kytos-end-to-end-tests]# python3 -m pytest --timeout=180 tests -k test_10_undesired_link_and_max_path
================================================================================== test session starts ==================================================================================
platform linux -- Python 3.9.18, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/viniarck/repos/kytos-end-to-end-tests
plugins: anyio-3.6.2, timeout-2.2.0
timeout: 180.0s
collected 254 items / 252 deselected / 2 selected …
```
> chore: temporarily skip pathfinder test_10_undesired_link_and_max_path

- tests/test_e2e_05_topology.py
Related PR [#179](https://github.com/kytos-ng/topology/pull/179)
Added test for API endpoint that deletes link.
```
+ python3 -m pytest tests/ -k test_130_delete_link --reruns 0 -r fEr
collected 255 items / 254 deselected / 1 selected
tests/test_e2e_05_topology.py .                                          [100%]
```
> Added test for deleted links

- tests/test_e2e_05_topology.py
- tests/test_e2e_30_of_lldp.py
Closes #276 
Depends on topology PR [#181](https://github.com/kytos-ng/topology/pull/181)
An interface cannot be enabled if its switch is disabled. Fixed
```
Trying to run 'hello' command on MongoDB...
Ran 'hello' command on MongoDB successfully. It's ready!
+ python3 -m pytest tests/ -k 'test_050_enabling_interface_persistent or test_060_enabling_and_disabling_all_interfaces_on_a_switch_persistent or test_070_disabling_interface_persistent or test_080_disabling_all_interfaces_on_a_switch_persistent or test_020_enable_of_lldp' --reruns 0 -r fEr
collected 255 items / 250 deselected …
```
> Fixed requirements for enabling

- tests/test_e2e_01_kytos_startup.py
Related to https://github.com/amlight/kytos-docker/issues/31
removed `flow_stats` from expected installed napps (up to this point we were maintaining both `kytos_stats` and `flow_stats`)
Results with this branch and docker's repo branch removing `flow_stats`:
```
collected 255 items
tests/test_e2e_05_topology.py ...................                        [  8%]
tests/test_e2e_10_mef_eline.py …
```
> chore: rm `flow_stats`

- tests/test_e2e_16_mef_eline.py
Closes #279.
This adds in a test for not_ownership, by requesting a dynamic path EVC with not_ownership as part of its mandatory constraints.
> Add in test for not_ownership

- tests/test_e2e_50_maintenance.py
There was an issue with the filtering of interfaces in maintenance that was not caught by the unit tests nor the e2e tests. With these new added tests similar issues/bugs should be caught by the e2e tests as well.
I just rewrote the unit test code so that it worked as an e2e test.
```
Attaching to kytos-end-to-end-tests_kytos_1
kytos_1        | Starting enhanced syslogd: rsyslogd.
kytos_1        | /etc/openvswitch/conf.db does not exist ... (warning).
kytos_1        | Creating empty database /etc/openvswitch/conf.db.
kytos_1        | Starting ovsdb-server.
kytos_1        | Configuring Open vSwitch system IDs.
kytos_1        | Starting ovs-vswitchd.
kytos_1        | Enabling remote OVSDB managers.
kytos_1        | + '[' -z '' ']'
kytos_1        | + '[' -z '' ']'
kytos_1        | + echo …
```
> Added additional coverage to maintenance e2e tests

- tests/test_e2e_05_topology.py
- tests/test_e2e_11_mef_eline.py
Closes #293
Minor changes due to python update
Depending in:
- [kytos PR](https://github.com/kytos-ng/kytos/pull/460)
- [kytos-docker PR](https://github.com/amlight/kytos-docker/pull/35)
```
platform linux -- Python 3.11.2, pytest-7.2.1, pluggy-1.4.0
collected 261 items
tests/test_e2e_05_topology.py ....................                       [  8%]
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 23%]
tests/test_e2e_11_mef_eline.py ......                                    [ 26%]
tests/test_e2e_12_mef_eline.py .....Xx. …
```
> Updated python

- tests/test_e2e_05_topology.py
Closes #295
Best guess is that `of_lldp` does not [free vlans](https://github.com/kytos-ng/of_lldp/blob/b09b598d37ac920bfb0fcad420a70943fab59d30/main.py#L278) fast enough. So when a switch is deleted, vlans appeared to be used.
From [gitlab](https://gitlab.ampath.net/amlight/kytos-end-to-end-tester/-/jobs/61314)
```
platform linux -- Python 3.11.2, pytest-8.1.1, pluggy-1.4.0
collected 261 items
tests/test_e2e_05_topology.py ....................                       [  8%]
tests/test_e2e_10_mef_eline.py …
```
> Added sleep

- tests/test_e2e_05_topology.py
- tests/test_e2e_06_topology.py
Closes #299
Isolated last test so it not affected by other tests
```
+ python3 -m pytest tests/test_e2e_06_topology.py --reruns 0 -r fEr
platform linux -- Python 3.11.2, pytest-8.1.1, pluggy-1.4.0
tests/test_e2e_06_topology.py .                                          [100%]
```
```
+ python3 -m pytest tests/test_e2e_05_topology.py --reruns 0 -r fEr
platform linux -- Python 3.11.2, pytest-8.1.1, pluggy-1.4.0
collected 21 items
tests/test_e2e_05_topology.py …
```
> Isolated last topology test

- README.rst
- docker-compose.local.yml
- docker-compose.yml
- requirements/requirements-local.txt
Closes #303
Updated the requirements from the local tests.
Updated to MongoDB 7.0
Before updating to 7.0, be sure to download the latest MongoDB package.
To run End-to-End-tests, the containers must be stopped and deleted. If e2e tests had been executed before the existing containers would be `kytos-end-to-end-tests-kytos-1`, `mongo-test-rs-init`, `mongo1t`, `mongo2t` and `mongo3t`:
```
CONTAINER ID   IMAGE                 COMMAND                  CREATED       STATUS                   PORTS                                                      NAMES
34ba9c958311   amlight/kytos:aldo2   "/docker-entrypoint.…"   3 hours ago   Exited (0) 3 hours ago                                                              kytos-end-to-end-tests-kytos-1
c6a6d07badef   mongo:7.0 …
```
> Updated to mongo 7.0

- tests/test_e2e_40_sdntrace.py
Closes #306
Depends on this [PR](https://github.com/kytos-ng/sdntrace/pull/78)
Added versioning to `sdntrace` API requests
N/A
```
+ python3 -m pytest tests/test_e2e_40_sdntrace.py --reruns 2 -r fEr
collected 14 items
tests/test_e2e_40_sdntrace.py ..............                             [100%]
```
> Added versioning to sdntrace requests

- tests/test_e2e_06_topology.py
Closes #309 
Closes #305 
Closes #310 
As pointed out by Italo, amlight topology did not have enough time to setup links. The time was increased from 10 to 20
Tested multiple times in [gitlab](https://gitlab.ampath.net/amlight/kytos-end-to-end-tester/-/jobs/67518)
N/A
> Added more time to setup Amlight topology

- tests/test_e2e_10_mef_eline.py
- tests/test_e2e_12_mef_eline.py
Closes #316 
Based on `mef_eline` PR [#475](https://github.com/kytos-ng/mef_eline/pull/475)
Updated EVC patching
N/A
```
collected 265 items
tests/test_e2e_05_topology.py ..................                         [  7%]
tests/test_e2e_06_topology.py ....                                       [  9%]
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 24%]
tests/test_e2e_11_mef_eline.py ......                                    [ 26%] …
```
> Updated payload for EVC patching

- tests/test_e2e_16_mef_eline.py
Closes #322 
Added test for `old_path` deletion. An evc is created with `current_path` and `failover_path`. Disabling an interface from `failover_path` will trigger the event `kytos/mef_eline.cleanup_evcs_old_path` which should clear `failover_path` flows.
N/A
```
+ python3 -m pytest tests/ -k test_e2e_16_mef_eline.py --reruns 0 -r fEr
collected 267 items / 265 deselected / 2 selected
tests/test_e2e_16_mef_eline.py ..                                        [100%]
```
> Added test that triggers old_path cleanup

- tests/test_e2e_70_kytos_stats.py
Closes #325 
- Enhanced both `test_025_packet_count_per_flow` and `test_030_bytes_count_per_flow` test cases to be less flaky by adding an extra time sleep and refactoring the data comparison to be less strict. 
I ran these two test cases 3 times on the CI:
```
+ python3 -m pytest tests/test_e2e_70_kytos_stats.py -k per_flow --reruns 2 -r fEr
collected 8 items / 6 deselected / 2 selected
tests/test_e2e_70_kytos_stats.py ..                                      [100%]
------------------------------- start/stop times …
```
> fix: enhanced TestE2EKytosStats flaky test cases

- tests/test_e2e_10_mef_eline.py
Closes #332
Using old test to test `primary_path` deployment into `current_path`
N/A
```
+ python3 -m pytest tests/ -k test_130_patch_primary_path --reruns 2 -r fEr
collected 267 items / 266 deselected / 1 selected
```
> Correcting primary_path test

- tests/test_e2e_20_flow_manager.py
Closes #330 
Introduced tests for
- Error 404 `POST /api/kytos/flow_manager/v2/flows_by_switch/`
- Error 404 `POST /api/kytos/flow_manager/v2/flows` and a list of switches
- Installation and deletion for `/api/kytos/flow_manager/v2/flows_by_switch/`
- Installation and deletion for `/api/kytos/flow_manager/v2/flows` and a list of switches
N/A
```
+ python3 -m pytest tests/test_e2e_20_flow_manager.py --reruns 2 -r fEr
collected 26 items
tests/test_e2e_20_flow_manager.py ..........................             [100%]
```
All the e2e tests to be added
> Created tests for new api requests

- tests/test_e2e_31_of_lldp.py
Related to https://github.com/kytos-ng/of_lldp/pull/111
Augmented e2e to cover status and status_reason for livenesss
with this branch and the new e2e related test:
```
+ python3 -m pytest tests/ -k test_005_liveness_goes_down --reruns 2 -r fEr
collected 267 items / 266 deselected / 1 selected
tests/test_e2e_31_of_lldp.py .                                           [100%]
------------------------------- start/stop times -------------------------------
========== 1 passed, 266 deselected, 35 warnings in 91.46s (0:01:31) …
```
> augmented e2e to cover status and status_reason for liveness

- tests/test_e2e_10_mef_eline.py
Closes #335 
- e2e test cov for UNIs activation cases
- This is using PR https://github.com/kytos-ng/mef_eline/pull/573
```
+ python3 -m pytest tests/test_e2e_10_mef_eline.py -k uni_status --reruns 2 -r fEr
collected 42 items / 40 deselected / 2 selected
tests/test_e2e_10_mef_eline.py ..                                        [100%]
------------------------------- start/stop times -------------------------------
========== 2 passed, 40 deselected, 34 warnings in 275.83s (0:04:35) ===========
```
- mef_eline test suites
```
+ …
```
> e2e test cov for UNIs activation cases

- tests/test_e2e_14_mef_eline.py
Closes #337
Added tests when avoiding VLANS when redeploying EVCs for the cases:
- Dynamic EVC
- Static EVC with both primary_path and backup_path
- Static EVC with just primary_path
N/A
```
+ python3 -m pytest tests/ -k 'test_010_redeploy_avoid_vlan or test_020_redeploy_avoid_vlan_static_path or test_015_redeploy_avoid_primary_path' --reruns 0 -r fEr
collected 274 items / 271 deselected / 3 selected
tests/test_e2e_14_mef_eline.py ...                                       [100%]
```
> Added tests for avoiding VLAN when redeploying EVC

- tests/test_e2e_14_mef_eline.py
Closes #341 
Added test for case in issue. The only difference being that `sudo ifconfig s1-eth1 down` was replaced for a link. This link is the UNI of the EVC tested.
N/A
```
Ran 'hello' command on MongoDB successfully. It's ready!
+ python3 -m pytest tests/test_e2e_14_mef_eline.py -k test_025_uni_link_up_static_path --reruns 0 -r fEr
collected 5 items / 4 deselected / 1 selected
tests/test_e2e_14_mef_eline.py .                                         [100%]
```
```
============================= test session starts …
```
> Added test for link_up, static and empty path

- tests/test_e2e_17_mef_eline.py
Adds tests which validate consistency of kytos after link down events. Part of kytos-ng/mef_eline#583.
> Added tests for link down consistency

- tests/test_e2e_10_mef_eline.py
Modifies existing test to compare path values, before and after a link up on a static path with no dynamic backup.
Ran with kytos-ng/mef_eline#632.
Here are the E2E results:
```
+ python3 -m pytest tests/test_e2e_10_mef_eline.py::TestE2EMefEline::test_150_current_path_value_given_dynamic_backup_path_and_empty_primary_conditions
=================================================================== test session starts ===================================================================
platform linux -- Python 3.11.11, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/ktmi/Documents/kytos-project/kytos-end-to-end-tests
plugins: anyio-4.3.0 …
```
> Added comparison for path expected value.

- tests/test_e2e_12_mef_eline.py
Closes #349 
Just added a patching request to a deleted EVC expecting it to fail
N/A
```
+ python3 -m pytest tests/ -k test_delete_circuit_id_and_patch --reruns 0 -r fEr
collected 280 items / 279 deselected / 1 selected
tests/test_e2e_12_mef_eline.py .                                         [100%]
```
> Update delete test by adding a patch

- tests/test_e2e_20_flow_manager.py
- tests/test_e2e_50_maintenance.py
Closes #346 
Added flow mismatching test by installing a miss  flow and trying to deleted it with another flow that should not match.
```
"flows": [{
"table_id": 0,
"match": {"dl_src": "ee:ee:ee:ee:ee:01"}
}]
```
N/A
Run the test with branch [e2e/flow_match](https://github.com/kytos-ng/flow_manager/compare/master...kytos-ng:flow_manager:e2e/flow_match) which has the tested changes reverted. Error expected.
```
+ python3 -m pytest tests/ -k test_105_mismatch_miss_flow --reruns 0 -r fEr
collected 283 items / 282 deselected / 1 selected
tests/test_e2e_20_flow_manager.py F …
```
> Added flow mismatching test

- tests/test_e2e_15_mef_eline.py
Related to PR kytos-ng/kytos#551
Updates the tag range in some mef_eline tests to match the new default ranges.
Here are the results of the modified tests, while using PR kytos-ng/kytos#551.
```
kytos-1  | Starting enhanced syslogd: rsyslogd.
kytos-1  | /etc/openvswitch/conf.db does not exist ... (warning).
kytos-1  | Creating empty database /etc/openvswitch/conf.db.
kytos-1  | Starting ovsdb-server.
kytos-1  | rsyslogd: error during config processing: omfile: chown for file '/var/log/syslog' failed: Operation not permitted [v8.2302.0 try https://www.rsyslog.com/e/2207 ]
kytos-1  | Configuring Open vSwitch system IDs.
kytos-1  | Starting ovs-vswitchd.
kytos-1  | Enabling remote OVSDB managers.
kytos-1  | + '[' -z '' ']'
kytos-1  | + '[' -z '' ']'
kytos-1  | + echo 'There is no NAPPS_PATH …
```
> Adjusted tests for change in default tag range

- tests/test_e2e_14_mef_eline.py
Closes #347 
Removed x mark in creation of an EVC with NNIs as UNIs
N/A
With branch `feature/evc_paths` from [PR](https://github.com/kytos-ng/mef_eline/pull/644)
```
+ python3 -m pytest tests/ -k test_005_create_evc_on_nni --reruns 0 -r fEr
collected 280 items / 279 deselected / 1 selected
tests/test_e2e_14_mef_eline.py .                                         [100%]
```
All other other tests in the file
```
+ python3 -m pytest tests/test_e2e_14_mef_eline.py --reruns 0 -r fEr
platform linux -- …
```
> [test]: Remove x mark from EVC NNI test.

- tests/test_e2e_10_mef_eline.py
Closes #348 
Redeploy active EVC and check if its `current_path` did not changed.
N/A
```
+ python3 -m pytest tests/ -k test_145_current_path_value_given_dynamic_backup_path_and_empty_primary_conditions --reruns 0 -r fEr
collected 280 items / 279 deselected / 1 selected
```
> Update test to redeploy active EVC

- tests/helpers.py
- tests/test_e2e_05_topology.py
Closes #360
This tests needs two branches:
of_core -> bug/replaced_interface from [PR](https://github.com/kytos-ng/of_core/pull/149)
topology -> bug/link_order from [PR](https://github.com/kytos-ng/topology/pull/255)
N/A
```
+ python3 -m pytest tests/ -k test_130_mismatched_links --reruns 0 -r fEr
collected 285 items / 284 deselected / 1 selected
tests/test_e2e_05_topology.py .                                          [100%]
```
All the tests
```
platform …
```
> Added test for mismatched links

- tests/test_e2e_10_mef_eline.py
Closes #362 
- Related to https://github.com/kytos-ng/mef_eline/pull/673
- Ran this augmented test case with this branch:
```
+ python3 -m pytest tests/ -k test_120_patch_queue_id --reruns 2 -r fEr
collected 284 items / 283 deselected / 1 selected
../../../../usr/local/lib/python3.11/dist-packages/kytos/core/config.py:254 …
```
> tests: augmented test_120_patch_queue_id to cover set_queue order

- tests/test_e2e_31_of_lldp.py
- tests/test_e2e_70_kytos_stats.py
Closes #366 
- Added `test_040_port_stats_tx_rx_packets` test case; initial e2e test coverage for https://github.com/kytos-ng/kytos_stats/issues/24
Ran this test case with this branch and the `kytos_stats` related branch that @italovalcy is working on
```
Ran 'hello' command on MongoDB successfully. It's ready!
+ python3 -m pytest tests/ -k test_040_port_stats_tx_rx_packets --reruns 2 -r fEr
collected 286 items / 285 deselected / 1 selected
tests/test_e2e_70_kytos_stats.py .                                       [100%] …
```
> feat: cover GET /api/amlight/kytos_stats/v1/port/stats endpoint

- tests/test_e2e_10_mef_eline.py
Closes #374 
Checking for qinq encapsulation in existent tests.
N/A
```
+ python3 -m pytest tests/ -k 'test_175_create_100_untagged_evc or test_025_create_evc_different_tags_each_side' --reruns 0 -r fEr
collected 287 items / 285 deselected / 2 selected
tests/test_e2e_10_mef_eline.py ..                                        [100%]
```
All the tests
```
plugins: rerunfailures-13.0, …
```
> Made sure that qinq is not present in flows

- tests/test_e2e_18_mef_eline.py
Closes #391
Fix a single missing line, also remove unused code.
Updated results:
```
kytos-1  | Starting enhanced syslogd: rsyslogd.
kytos-1  | /etc/openvswitch/conf.db does not exist ... (warning).
kytos-1  | Creating empty database /etc/openvswitch/conf.db.
kytos-1  | Starting ovsdb-server.
kytos-1  | rsyslogd: error during config processing: omfile: chown for file '/var/log/syslog' failed: Operation not permitted [v8.2302.0 try https://www.rsyslog.com/e/2207 ]
kytos-1  | Configuring Open vSwitch system IDs.
kytos-1  | Starting ovs-vswitchd.
kytos-1  | Enabling remote OVSDB managers.
kytos-1  | + '[' -z '' ']'
kytos-1  | + '[' -z '' ']'
kytos-1  | + echo 'There is no NAPPS_PATH specified. Default will be used.'
kytos-1  | There is no NAPPS_PATH specified. Default will be used.
kytos-1 …
```
> Fix missing return statement in assert_tag_used_by_interface

- tests/test_e2e_18_mef_eline.py
Part of kytos-ng/mef_eline#698
Adds tests for checking that evcs are deactivated if their UNIs are down or disabled. Also adds in a missing return for the assert statements added in my last PR (whoops).
Both new tests fail. as the new expected behaviour hasn't been implemented yet.
```
kytos-1  | Starting enhanced syslogd: rsyslogd.
kytos-1  | /etc/openvswitch/conf.db does not exist ... (warning).
kytos-1  | Creating empty database /etc/openvswitch/conf.db.
kytos-1  | rsyslogd: error during config processing: omfile: chown for file '/var/log/syslog' failed: Operation not permitted [v8.2302.0 try https://www.rsyslog.com/e/2207 ]
kytos-1  | Starting ovsdb-server.
kytos-1  | Configuring Open vSwitch system IDs.
kytos-1  | Starting ovs-vswitchd.
kytos-1  | Enabling remote OVSDB managers. …
```
> Test interface down and interface disable effect on EVCs
